# Generated by Django 2.2.2 on 2022-03-08 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='曲名(正式名称)')),
                ('short_title', models.CharField(max_length=20, verbose_name='曲名(略称)')),
                ('start_date', models.DateField(verbose_name='練習開始日')),
                ('end_date', models.DateField(verbose_name='練習終了日')),
                ('category', models.IntegerField(choices=[(1, '前'), (2, '中'), (3, 'メイン'), (4, 'その他')])),
            ],
            options={
                'verbose_name': '曲',
                'verbose_name_plural': '曲',
                'db_table': 'music',
                'ordering': ['end_date'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=5, verbose_name='パート')),
                ('comment', models.TextField(blank=True, max_length=40, null=True, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Music', verbose_name='曲')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='回答者')),
            ],
            options={
                'verbose_name_plural': 'Stage',
            },
        ),
    ]
