# Generated by Django 4.0.3 on 2022-03-12 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_music_id_alter_stage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='期の名前')),
                ('start_date', models.DateField(verbose_name='開始年月日')),
                ('end_date', models.DateField(verbose_name='終了年月日')),
            ],
            options={
                'verbose_name': '期',
                'verbose_name_plural': '期',
                'db_table': 'term',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='演奏会名')),
                ('date', models.DateField(verbose_name='本番日程')),
                ('hall', models.CharField(max_length=40, verbose_name='ホール')),
                ('url', models.URLField(blank=True, null=True, verbose_name='ホールURL(地図など)')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.term', verbose_name='期')),
            ],
            options={
                'verbose_name': '演奏会',
                'verbose_name_plural': '演奏会',
                'db_table': 'concert',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='music',
            name='concert',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.concert', verbose_name='演奏会'),
        ),
    ]
