# Generated by Django 4.0.3 on 2022-03-13 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_term_concert_music_concert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='concert',
        ),
        migrations.AddField(
            model_name='music',
            name='term',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.term', verbose_name='練習期'),
        ),
    ]
