# Generated by Django 4.0.3 on 2022-03-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='part',
            table='part',
        ),
    ]
