# Generated by Django 3.0.6 on 2020-07-03 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200701_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='楽器')),
                ('section_name', models.CharField(max_length=10, verbose_name='セクション')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Instrument', verbose_name='パート'),
        ),
    ]
