# Generated by Django 3.0.6 on 2020-07-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200703_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='short_name',
            field=models.CharField(default='?', max_length=10, verbose_name='楽器の略称'),
        ),
    ]
