# Generated by Django 2.2.2 on 2022-03-08 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='練習名')),
                ('location', models.CharField(blank=True, max_length=40, null=True, verbose_name='練習場所')),
                ('url', models.URLField(null=True, verbose_name='url')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='練習内容')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='練習日')),
                ('start_at', models.TimeField(default='14:00:00', verbose_name='開始時刻')),
                ('end_at', models.TimeField(default='17:00:00', verbose_name='終了時刻')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('music', models.ManyToManyField(null=True, to='music.Music', verbose_name='練習する曲')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name_plural': 'Schedule',
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=5, verbose_name='回答')),
                ('comment', models.TextField(blank=True, max_length=40, null=True, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Schedule', verbose_name='練習予定')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='回答者')),
            ],
            options={
                'verbose_name_plural': 'Reaction',
            },
        ),
    ]
