# Generated by Django 3.0.6 on 2020-06-18 04:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='練習名')),
                ('location', models.CharField(blank=True, max_length=40, null=True, verbose_name='練習場所')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='練習内容')),
                ('date', models.DateField(default=datetime.date(2020, 6, 18), verbose_name='練習日')),
                ('start_at', models.DateTimeField(default=datetime.datetime(2020, 6, 18, 13, 46, 7, 898929), verbose_name='開始時刻')),
                ('end_at', models.DateTimeField(default=datetime.datetime(2020, 6, 18, 13, 46, 7, 898945), verbose_name='終了時刻')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name_plural': 'Schedule',
            },
        ),
    ]
