# Generated by Django 3.0.6 on 2020-06-20 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.date(2020, 6, 20), verbose_name='練習日'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_at',
            field=models.TimeField(default=datetime.datetime(2020, 6, 20, 22, 31, 25, 641942), verbose_name='終了時刻'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_at',
            field=models.TimeField(default=datetime.datetime(2020, 6, 20, 22, 31, 25, 641927), verbose_name='開始時刻'),
        ),
    ]
