# Generated by Django 4.0.3 on 2022-03-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='music',
            field=models.ManyToManyField(null=True, to='music.music', verbose_name='練習する曲'),
        ),
    ]
