# Generated by Django 4.0.3 on 2022-03-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_music_id_alter_stage_id'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='music',
            field=models.ManyToManyField(to='music.music', verbose_name='練習する曲'),
        ),
    ]
