# Generated by Django 3.0.6 on 2020-06-20 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20200620_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_at',
            field=models.TimeField(default=datetime.datetime(2020, 6, 20, 22, 49, 51, 596327), verbose_name='終了時刻'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_at',
            field=models.TimeField(default=datetime.datetime(2020, 6, 20, 22, 49, 51, 596310), verbose_name='開始時刻'),
        ),
    ]
