# Generated by Django 4.0.3 on 2022-03-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
    ]
