# Generated by Django 4.0.3 on 2022-03-14 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_music_concert_music_term'),
        ('schedule', '0003_alter_schedule_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='etc',
            field=models.BooleanField(default=False, verbose_name='その他'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='mae',
            field=models.BooleanField(default=False, verbose_name='前曲'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='main',
            field=models.BooleanField(default=False, verbose_name='メイン曲'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='naka',
            field=models.BooleanField(default=False, verbose_name='中曲'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.term', verbose_name='該当する練習期'),
        ),
    ]
