# Generated by Django 3.0.6 on 2020-06-20 22:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0003_auto_20200620_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.date(2020, 6, 21), verbose_name='練習日'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_at',
            field=models.TimeField(default=datetime.datetime(2020, 6, 21, 7, 10, 23, 972722), verbose_name='終了時刻'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_at',
            field=models.TimeField(default=datetime.datetime(2020, 6, 21, 7, 10, 23, 972707), verbose_name='開始時刻'),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=5, verbose_name='回答')),
                ('comment', models.TextField(blank=True, max_length=40, null=True, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Schedule', verbose_name='練習予定')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='回答者')),
            ],
        ),
    ]
