# Generated by Django 3.0.6 on 2020-06-20 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20200621_0710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reaction',
            options={'verbose_name_plural': 'Reaction'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_at',
            field=models.TimeField(default=datetime.datetime(2020, 6, 21, 7, 43, 14, 404917), verbose_name='終了時刻'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_at',
            field=models.TimeField(default=datetime.datetime(2020, 6, 21, 7, 43, 14, 404902), verbose_name='開始時刻'),
        ),
    ]
