# Generated by Django 3.0.6 on 2020-07-01 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20200621_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.date(2020, 7, 1), verbose_name='練習日'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_at',
            field=models.TimeField(default=datetime.datetime(2020, 7, 1, 23, 47, 33, 148642), verbose_name='終了時刻'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_at',
            field=models.TimeField(default=datetime.datetime(2020, 7, 1, 23, 47, 33, 148624), verbose_name='開始時刻'),
        ),
    ]
