# Generated by Django 3.0.6 on 2020-07-03 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20200701_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='練習日'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_at',
            field=models.TimeField(default='17:00:00', verbose_name='終了時刻'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_at',
            field=models.TimeField(default='14:00:00', verbose_name='開始時刻'),
        ),
    ]
